create table customer (
   customerid  number
      generated by default as identity
   primary key,
   name        varchar2(100),
   email       varchar2(100),
   phonenumber varchar2(20)
);

-- PRODUCT TABLE
create table product (
   productid       number
      generated by default as identity
   primary key,
   name            varchar2(100),
   brand           varchar2(100),
   price           number(10,2),
   quantityinstock number
);

-- ORDER TABLE
create table order_info (
   orderid     number
      generated by default as identity
   primary key,
   orderdate   date,
   totalamount number(10,2),
   customerid  number,
   constraint fk_order_customer foreign key ( customerid )
      references customer ( customerid )
);

-- ORDER ITEM TABLE
create table orderitem (
   orderitemid number
      generated by default as identity
   primary key,
   quantity    number,
   subtotal    number(10,2),
   orderid     number,
   productid   number,
   constraint fk_orderitem_order foreign key ( orderid )
      references order_info ( orderid ),
   constraint fk_orderitem_product foreign key ( productid )
      references product ( productid )
);

-- RECEIPT TABLE
create table receipt (
   receiptid   number
      generated by default as identity
   primary key,
   receiptdate date,
   totalamount number(10,2),
   orderid     number,
   constraint fk_receipt_order foreign key ( orderid )
      references order_info ( orderid )
);
alter session set container = xepdb1;

select table_name
  from user_tables;