CREATE TABLE Customer (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100),
    Email VARCHAR2(100),
    PhoneNumber VARCHAR2(20)
);

-- PRODUCT TABLE
CREATE TABLE Product (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100),
    Brand VARCHAR2(100),
    Price NUMBER(10, 2),
    QuantityInStock NUMBER
);

-- ORDER TABLE
CREATE TABLE "Order" (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderDate DATE,
    TotalAmount NUMBER(10, 2),
    CustomerID NUMBER,
    CONSTRAINT fk_order_customer FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

-- ORDER ITEM TABLE
CREATE TABLE OrderItem (
    OrderItemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Quantity NUMBER,
    Subtotal NUMBER(10, 2),
    OrderID NUMBER,
    ProductID NUMBER,
    CONSTRAINT fk_orderitem_order FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID),
    CONSTRAINT fk_orderitem_product FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);

-- RECEIPT TABLE
CREATE TABLE Receipt (
    ReceiptID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReceiptDate DATE,
    TotalAmount NUMBER(10, 2),
    OrderID NUMBER,
    CONSTRAINT fk_receipt_order FOREIGN KEY (OrderID) REFERENCES "Order"(OrderID)
);
ALTER SESSION SET CONTAINER = XEPDB1;

SELECT table_name FROM user_tables; 