CREATE USER dogfood IDENTIFIED BY password123;


GRANT CONNECT, RESOURCE TO dogfood_user;


ALTER USER dogfood_user DEFAULT TABLESPACE users;
GRANT UNLIMITED TABLESPACE TO dogfood_user;

SHOW CON_NAME;
SELECT name, open_mode FROM v$pdbs;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER dogfood_user IDENTIFIED BY password123;
GRANT CONNECT, RESOURCE TO dogfood_user;
ALTER USER dogfood_user DEFAULT TABLESPACE users;
GRANT UNLIMITED TABLESPACE TO dogfood_user;

